credentials:
  usernames:
    shabar:
      email: your mail id
      name: name
      password: 'Password'  # Hashed version

cookie:
  expiry_days: 1
  key: some_signature_key
  name: secure_iot_cookie

preauthorized:
  emails:
    - jafsamnazsha@gmail.com
